/*
 * crypto_utils.c
 * AES-CBC decryptor for encrypted face embeddings
 * Compatible with embeddings generated by gen_refset_tflite.py
 *
 * Author: Muazzam & ChatGPT
 * Date: 2025-10-09
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#if __has_include("tinyAES/aes.h")
  #include "tinyAES/aes.h"
#elif __has_include("aes/aes.h")
  #include "aes/aes.h"
#else
  #error "AES header not found. Make sure tinyAES/aes.h or aes/aes.h is in include path."
#endif

#include "crypto_utils.h"
#include "app_config.h"

/* ============================================================================
 *  AES Configuration — MUST MATCH PYTHON SCRIPT
 *  ============================================================================
 *  AES_KEY = 603DEB1015CA71BE2B73AEF0857D77811F352C073B6108D72D9810A30914DFF4
 *  AES_IV  = 000102030405060708090A0B0C0D0E0F
 * -------------------------------------------------------------------------- */

static const uint8_t FR_AES_KEY_16[16] = {
    0x60, 0x3D, 0xEB, 0x10, 0x15, 0xCA, 0x71, 0xBE,
    0x2B, 0x73, 0xAE, 0xF0, 0x85, 0x7D, 0x77, 0x81
};

static const uint8_t FR_AES_IV_16[16] = {
    0x00, 0x01, 0x02, 0x03,
    0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F
};

/* ============================================================================
 *  Core Decryptor
 *  ============================================================================
 */

static void fr_aes_cbc_decrypt_inplace(uint8_t *buf, size_t len)
{
    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, FR_AES_KEY_16, FR_AES_IV_16);
    AES_CBC_decrypt_buffer(&ctx, buf, len);
}

/**
 * @brief Decrypt a single 2048-byte embedding ciphertext into float32[512].
 * @param cipher          Pointer to ciphertext data.
 * @param len_bytes       Ciphertext length (must be 2048).
 * @param out_f32         Output float array (size >= 512).
 * @param out_f32_capacity Capacity of output buffer in floats.
 * @return 0 on success, -1 on invalid args or length mismatch.
 */
int FR_DecryptEmbedding_ToFloat(const uint8_t *cipher, size_t len_bytes,
                                float *out_f32, size_t out_f32_capacity)
{
    if (!cipher || !out_f32) return -1;
    if ((len_bytes % 16) != 0 || len_bytes != 2048) return -1;
    if (out_f32_capacity < 512) return -1;

    uint8_t tmp[2048];
    memcpy(tmp, cipher, 2048);
    fr_aes_cbc_decrypt_inplace(tmp, 2048);
    memcpy(out_f32, tmp, 2048);

    return 0;
}

/* ============================================================================
 *  Reference Set Bulk Decryptor
 *  ============================================================================
 */

#include "app_config.h"
#include <stdint.h>

/* Extern symbols from combined_refset.c */
typedef struct { const char* name; const uint8_t* data; int dim; } EmbRec;
extern EmbRec* g_ref_set;
extern int     g_ref_set_count;


/* Provide backing storage for decrypted float vectors (max 128 embeddings) */
static float s_dec_store_max[128][512];

/**
 * @brief Decrypt all embeddings in g_ref_set (runs once at startup).
 */
void FR_DecryptAllRefsetOnce(void)
{
    printf("[DEC] Starting AES-CBC decryption of %d reference embeddings...\r\n", g_ref_set_count);

    for (int i = 0; i < g_ref_set_count; ++i)
    {
        const uint8_t *enc = (const uint8_t*)g_ref_set[i].data;
        const int dim = g_ref_set[i].dim;
        const size_t need = (size_t)dim * sizeof(float);

        if (dim != 512 || need != 2048)
        {
            printf("[DEC] Skipping invalid dim=%d for %s\r\n",
                   dim, g_ref_set[i].name ? g_ref_set[i].name : "?");
            continue;
        }

        if (FR_DecryptEmbedding_ToFloat(enc, need, s_dec_store_max[i], 512) == 0)
        {
            g_ref_set[i].data = s_dec_store_max[i];
            printf("[DEC] OK: %s decrypted.\r\n", g_ref_set[i].name ? g_ref_set[i].name : "?");
        }
        else
        {
            printf("[DEC] FAIL: %s\r\n", g_ref_set[i].name ? g_ref_set[i].name : "?");
        }
    }

    printf("[DEC] All reference embeddings decrypted.\r\n");
}
