#!/usr/bin/env python3
import argparse, os, glob, pathlib
import numpy as np
from PIL import Image

# Prefer tflite-runtime; fall back to TF Lite interpreter
try:
    import tflite_runtime.interpreter as tflite
    _TFLITE = True
except Exception:
    import tensorflow as tf
    tflite = tf.lite
    _TFLITE = False


def get_qparams(tensor_detail):
    """
    Return (scale, zero_point) robustly across TF and tflite-runtime.
    """
    if "quantization" in tensor_detail and tensor_detail["quantization"]:
        sc, zp = tensor_detail["quantization"]
        return float(sc), int(zp)
    qp = tensor_detail.get("quantization_parameters", None)
    if qp and len(qp.get("scales", [])) == 1 and len(qp.get("zero_points", [])) == 1:
        return float(qp["scales"][0]), int(qp["zero_points"][0])
    return 0.0, 0  # unquantized


def center_square_resize_to_minus1_1(path, size=(160, 160)):
    """
    Load image, center-square crop, resize, return HWC float32 in [-1, 1].
    """
    im = Image.open(path).convert("RGB")
    w, h = im.size
    side = min(w, h)
    x0 = (w - side) // 2
    y0 = (h - side) // 2
    im = im.crop((x0, y0, x0 + side, y0 + side))
    im = im.resize(size, Image.BILINEAR)
    arr = np.asarray(im, dtype=np.float32)  # [0..255]
    return arr * (1.0 / 127.5) - 1.0        # [-1, 1]


def prepare_input_tensor(x_minus1_1_hwc, in_shape, in_dtype, in_scale, in_zp):
    """
    Map HWC float [-1,1] -> model input dtype and layout (NHWC/NCHW).
    Supports: uint8, int8, float32/float16.
    """
    if len(in_shape) != 4:
        raise SystemExit(f"Unexpected input rank: {in_shape}")
    n, d1, d2, d3 = in_shape
    if d3 == 3:
        layout = "NHWC"
    elif d1 == 3:
        layout = "NCHW"
    else:
        raise SystemExit(f"Cannot infer layout from shape {in_shape}")

    # Quantized (uint8)
    if in_dtype == np.uint8:
        if in_scale == 0.0:
            raise SystemExit("Model reports uint8 input but zero scale; re-export with proper calibration.")
        q = np.round(x_minus1_1_hwc / in_scale + in_zp).astype(np.int32)
        q = np.clip(q, 0, 255).astype(np.uint8)
        if layout == "NHWC":
            q = q[None, ...]
        else:
            q = np.transpose(q, (2, 0, 1))[None, ...]
        return q

    # Quantized (int8)
    if in_dtype == np.int8:
        if in_scale == 0.0:
            raise SystemExit("Model reports int8 input but zero scale; re-export with proper calibration.")
        q = np.round(x_minus1_1_hwc / in_scale + in_zp).astype(np.int32)
        q = np.clip(q, -128, 127).astype(np.int8)
        if layout == "NHWC":
            q = q[None, ...]
        else:
            q = np.transpose(q, (2, 0, 1))[None, ...]
        return q

    # Float input (dynamic-range models)
    if in_dtype in (np.float32, np.float16):
        x = x_minus1_1_hwc.astype(np.float32)
        if layout == "NHWC":
            x = x[None, ...]
        else:
            x = np.transpose(x, (2, 0, 1))[None, ...]
        return x

    raise SystemExit(f"Unsupported input dtype: {in_dtype}")


def dequantize_output(y_raw, out_dtype, out_scale, out_zp):
    """
    Map model output tensor to float32 embedding.
    Supports int8 (with scale/zp) and float32/float16 outputs.
    """
    if out_dtype == np.int8:
        return (y_raw.astype(np.float32) - float(out_zp)) * float(out_scale)
    if out_dtype in (np.float32, np.float16):
        return y_raw.astype(np.float32)
    raise SystemExit(f"Unsupported output dtype: {out_dtype}")


def l2_normalize(v, eps=1e-9):
    n = np.sqrt(np.sum(v * v)) + eps
    return v / n


def emit_c_struct(out_c, subject, vecs):
    """
    Emit a C table that matches the firmware expectations:
      - includes app_config.h for FR_EMB_SIZE
      - single subject name repeated (e.g. "Muazzam")
      - EmbRec { name, data, dim }
    """
    dim = len(vecs[0])
    with open(out_c, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_refset_tflite.py — DO NOT EDIT */\n")
        f.write("#include <stddef.h>\n")
        f.write("#include \"app_config.h\"\n\n")
        f.write("#ifndef FR_EMB_SIZE\n")
        f.write(f"#define FR_EMB_SIZE {dim}\n")
        f.write("#endif\n\n")
        f.write("typedef struct { const char* name; const float* data; int dim; } EmbRec;\n\n")
        f.write(f"#define REF_NAME \"{subject}\"\n\n")

        for i, v in enumerate(vecs):
            f.write(f"static const float emb_{i}[] = {{\n  ")
            for k, val in enumerate(v):
                sep = ", "
                if (k + 1) % 8 == 0: sep = ",\n  "
                if k + 1 == len(v):  sep = "\n"
                f.write(f"{val:.8f}f{sep}")
            f.write("};\n\n")

        f.write("const EmbRec g_ref_set[] = {\n")
        for i in range(len(vecs)):
            f.write(f"  {{ REF_NAME, emb_{i}, FR_EMB_SIZE }},\n")
        f.write("};\n")
        f.write("const int g_ref_set_count = (int)(sizeof(g_ref_set)/sizeof(g_ref_set[0]));\n")


def main():
    ap = argparse.ArgumentParser(
        description="Generate reference embeddings (C table) from a quantized TFLite FaceNet-like model."
    )
    ap.add_argument("--model", default="facenet_512_int_quant.tflite",
                    help="Path to TFLite model (default: facenet_512_int_quant.tflite)")
    ap.add_argument("--in_dir", default=".",
                    help="Folder with face crops (jpg/png/bmp). Default: current directory")
    ap.add_argument("--out_dir", default="output",
                    help="Folder to write outputs (default: output)")
    ap.add_argument("--size", type=int, default=160,
                    help="Square input size (default 160)")
    ap.add_argument("--subject", default="Muazzam",
                    help="Subject name stored for every embedding (default: Muazzam)")
    ap.add_argument("--no_l2norm", action="store_true",
                    help="Disable L2 normalization (enabled by default)")
    ap.add_argument("--save_npz", action="store_true",
                    help="Also save embeddings.npz for offline checks")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    out_txt = os.path.join(args.out_dir, "embeddings.txt")
    out_c   = os.path.join(args.out_dir, "embeddings_table.c")
    out_npz = os.path.join(args.out_dir, "embeddings.npz")

    # Interpreter
    interp = tflite.Interpreter(model_path=args.model)
    interp.allocate_tensors()

    in_det  = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]

    in_idx, out_idx     = in_det["index"], out_det["index"]
    in_dtype, out_dtype = in_det["dtype"], out_det["dtype"]
    in_shape            = list(in_det["shape"])
    in_scale, in_zp     = get_qparams(in_det)
    out_scale, out_zp   = get_qparams(out_det)

    print("[IO] IN :", in_dtype, "shape=", in_shape, "scale=", in_scale, "zp=", in_zp)
    print("[IO] OUT:", out_dtype, "scale=", out_scale, "zp=", out_zp)

    # Gather images (e.g., a.jpg ... e.jpg)
    exts = ("*.bmp", "*.png", "*.jpg", "*.jpeg")
    files = sorted(sum([glob.glob(os.path.join(args.in_dir, e)) for e in exts], []))
    if not files:
        raise SystemExit(f"No images found in {args.in_dir}")

    print(f"[INFO] Found {len(files)} image(s).")
    vecs = []
    labels = []
    with open(out_txt, "w", encoding="utf-8") as outf:
        for fp in files:
            x = center_square_resize_to_minus1_1(fp, size=(args.size, args.size))  # HWC [-1,1]
            tin = prepare_input_tensor(x, in_shape, in_dtype, in_scale, in_zp)

            interp.set_tensor(in_idx, tin)
            interp.invoke()
            y_raw = interp.get_tensor(out_idx).reshape(-1)  # int8 or float
            y = dequantize_output(y_raw, out_dtype, out_scale, out_zp)

            if not args.no_l2norm:
                y = l2_normalize(y)

            vecs.append(y.tolist())
            label = pathlib.Path(fp).stem
            labels.append(label)
            outf.write(label + "|" + str(y.shape[0]) + "|" + ",".join(f"{v:.6f}" for v in y.tolist()) + "\n")
            print(f"[OK] {os.path.basename(fp)}  dim={y.shape[0]}  L2={np.linalg.norm(y):.3f}")

    # Emit C table and optional NPZ
    emit_c_struct(out_c, args.subject, vecs)
    if args.save_npz:
        np.savez(out_npz, labels=np.array(labels), embeddings=np.array(vecs, dtype=np.float32))

    print(f"[DONE] Wrote:\n  - {out_c}\n  - {out_txt}")
    if args.save_npz:
        print(f"  - {out_npz}")
    print(f"[INFO] Quant (input) : scale={in_scale}  zp={in_zp}  dtype={in_dtype}  shape={in_shape}")
    print(f"[INFO] Quant (output): scale={out_scale} zp={out_zp} dtype={out_dtype}")


if __name__ == "__main__":
    main()
