#pragma once
/* Pull the generated header from st_ai_output/header */
#include "face_recognition.h"

#ifndef LL_ATON_FACE_RECOGNITION_IN_1_SIZE_BYTES
#error "Generated face_recognition.h not found in include path."
#endif

/* Derive FaceRec input size from generated bytes (handles 160x160 or 112x112) */
#if   (LL_ATON_FACE_RECOGNITION_IN_1_SIZE_BYTES == 76800u)   /* 160*160*3 */
  #define FR_IN_W   160
  #define FR_IN_H   160
#elif (LL_ATON_FACE_RECOGNITION_IN_1_SIZE_BYTES == 37632u)   /* 112*112*3 */
  #define FR_IN_W   112
  #define FR_IN_H   112
#else
  #error "Unsupported FaceRec input size; add a case in fr_model_cfg.h."
#endif

#define FR_EMB_SIZE 512   /* your model outputs 512-d int8 */

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
  _Static_assert(LL_ATON_FACE_RECOGNITION_OUT_1_SIZE_BYTES == FR_EMB_SIZE,
                 "Embedding size mismatch vs generated header.");
  _Static_assert(LL_ATON_FACE_RECOGNITION_IN_1_SIZE_BYTES == (FR_IN_W*FR_IN_H*3),
                 "Input bytes mismatch vs FR_IN_W/FR_IN_H.");
#endif

/* Typing flags your code uses */
#define FR_IN_IS_UINT8 1
#define FR_OUT_IS_INT8 1
